// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi22Rm3dVwzzr6M1Mm0Ev3Z9bnc8kkwC8',
    appId: '1:528824864505:web:fb08de851f19d1302e5c28',
    messagingSenderId: '528824864505',
    projectId: 'cmsc23-todo-app-vaarellano',
    authDomain: 'cmsc23-todo-app-vaarellano.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-vaarellano.appspot.com',
    measurementId: 'G-9RD83QZ7WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFK14H48QkANKYFB2vB_Kwgzv-04HHnw0',
    appId: '1:528824864505:android:189008b83d92ebf02e5c28',
    messagingSenderId: '528824864505',
    projectId: 'cmsc23-todo-app-vaarellano',
    storageBucket: 'cmsc23-todo-app-vaarellano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALY0lIceEftvD5jiTJO5VSdhe0OsILHZg',
    appId: '1:528824864505:ios:dd8fb44cb1800aa72e5c28',
    messagingSenderId: '528824864505',
    projectId: 'cmsc23-todo-app-vaarellano',
    storageBucket: 'cmsc23-todo-app-vaarellano.appspot.com',
    iosClientId: '528824864505-8i6pcmmtu6te29goovhksocfdl2b73cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALY0lIceEftvD5jiTJO5VSdhe0OsILHZg',
    appId: '1:528824864505:ios:dd8fb44cb1800aa72e5c28',
    messagingSenderId: '528824864505',
    projectId: 'cmsc23-todo-app-vaarellano',
    storageBucket: 'cmsc23-todo-app-vaarellano.appspot.com',
    iosClientId: '528824864505-8i6pcmmtu6te29goovhksocfdl2b73cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
